### ISSUE TITLE
Autocomplete based on transliteration of actual nick/name.

### ISSUE THREAD

**Issue by aviraldg** [element-hq/element-web#1294]
Examples:
- `eirian` would autocomplete to `エイリアン`
- `Uniaika` would autocomplete to `𝓤𝓷𝓲𝓪𝓲𝓴𝓪`

**Comment by ara4n** [comment]
if there's a good transliteration library that actually does the right thing for this, then 'yay'. otherwise, i'm not convinced - especially as we have click-to-insert these days. plus my katakana isn't good enough to have a hope in hell of knowing that the first letter of エイリアン should be transliterated to 'ei' rather than 'a', etc.

**Comment by t3chguy** [comment]
For the latter example this would be easy using unhomoglyph which we already use in js-sdk

**Comment by t3chguy** [comment]
This happened

![image](https://github.com/user-attachments/assets/69c06c49-7e6b-4829-b887-1eab7d41b271)
