### ISSUE TITLE
clicking 'restore from backup' in online backup goes and loads all your keys from the server without warning

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#15011]
i just stupidly hit the 'restore from backup' button, to see if it'd prompt me for a recovery passphrase/key or something. instead, it locked my element solid for ~10 minutes re-downloading all my megolm keys from the server and trying to re-import them. surely we should have a warning prompt to explain what it's about to do.  It's also very unclear when you'd ever want to use this (other than recovering from a bug?)

**Comment by anoadragon453** [comment]
This is a slightly less thorny issue today in that you can close the 'Restoring keys from backup" modal via an X in the corner, which follows the design mantra of "do an action, but allow the user to undo it".

**Comment by DMRobertson** [comment]
I just did this today after creating a new session in a desperate attempt to let me see encrypted messages on a new session.

What would have helped:

- This process taking place in the background, rather than a modal (#20694)
- Some kind of warning this will take a long time and lock up Element
- Some kind of ETA on the process completing, or a progress bar
- The ability to restore keys based on time range to cut down the duration

**Comment by richvdh** [comment]
> clicking 'restore from backup' in online backup goes and loads all your keys from the server without warning

Seems like it did what it says on the tin to me. I think really we should just remove the button. Part of https://github.com/element-hq/element-web/issues/26468
