### ISSUE TITLE
Consider changing Safari support policy

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#17965]
Our current policy of 'last 2 major versions' means we're supporting a Safari that is out of vendor support

**Comment by jryans** [comment]
What description of Safari / macOS support timelines are you referring to?

As for macOS itself, Apple generally supports the last 3 major releases, e.g. currently Big Sur (11.x), Catalina (10.15.x), and Mojave (10.14.x).

**Comment by turt2live** [comment]
I was going off this chart, but admittedly have no idea what versioning looks like in the Mac world:

![image](https://user-images.githubusercontent.com/1190097/125356164-11fbb080-e323-11eb-8994-a818a5b310b7.png)

**Comment by jryans** [comment]
I think that chart is trying to say Safari 14.1 is supported on all of the last 3 macOS major releases, which is why the date column has no end date.

Looking more directly at the [Safari 14.x section](https://en.wikipedia.org/wiki/Safari_version_history#Safari_14):

![image](https://user-images.githubusercontent.com/279572/125420296-de073c09-d4ec-44e4-81bf-0cd85f9e5f6f.png)

...it also seems to say the Safari 14.x major release is supported on the last 3 macOS major releases. Anyway, that's all just about which macOS releases Safari runs on. 

As for which _Safari_ releases we want to support, given that Safari is released on a much slower timescale than the other browsers (typically one major Safari release per year) and also tends to be the last browser to implement web platform features, I agree it might make sense to support only the current major release instead of the last 2 like other browsers.

**Comment by t3chguy** [comment]
We updated this to not say major versions of Safari at some point, so just `Last 2 versions of Safari` - codified also in browserslist conf
