### ISSUE TITLE
logout takes several seconds to take effect

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#18030]
if you click the logout button, you get hurled back into the app for a few seconds before it then suddenly kicks you out

**Comment by ara4n** [comment]
this has got so bad that the logout button doesn't seem to do anything; after about 5 minutes a logout dialog pops up; clicking 'okay' then in turn does nothing. i restarted the app, and it sat in a spinner having loaded; the JS console was full of 401s, so this time i tried to hit logout again, and this time it instantly threw me out.

**Comment by BillCarsonFr** [comment]
For some reason the react sdk is exporting all keys in order to know if there are megolm keys in storage:

https://github.com/matrix-org/matrix-react-sdk/blob/5983528a8d4e20db46638428984c9f3952ede8f3/src/components/structures/UserMenu.tsx#L262-L267

```
        if (!cli || !cli.isCryptoEnabled() || !(await cli.exportRoomKeys())?.length) {
            // log out without user prompt if they have no local megolm sessions
            defaultDispatcher.dispatch({ action: "logout" });
        } else {
            Modal.createDialog(LogoutDialog);
        }
```
This is a particularly bad way to check if there are keys that are not saved in backup...
