### ISSUE TITLE
Element R reports "Session key:	<not supported>"

### ISSUE THREAD

**Issue by julioromano** [element-hq/element-web#26378]
### Steps to reproduce

Dogfooding R from https://pr10080--matrix-react-sdk.netlify.app/
Logged in to the element.io HS and done SAS verification.

### Outcome

After successfully decrypting all content I can see in the security preferences: "Session key:	<not supported>"
Whilst on non-R Element it correctly spells out the session key.

### Browser information

Chrome Version 118.0.5993.70 (Official Build) (arm64)

### URL for webapp

https://pr10080--matrix-react-sdk.netlify.app/

### Homeserver

element.io

### Will you send logs?

No

**Comment by richvdh** [comment]
This is probably a 30 second fix.

**Comment by BillCarsonFr** [comment]
Let's remove it. It's a dev tool

**Comment by apotheon** [comment]
Are there any updates on this thirty-second fix?

**Comment by hax0rbana-adam** [comment]
I'm trying to help someone debug the dreaded Unable to Decrypt problem and this was the only thing that I could find that was different between her session (which can only decrypt messages after she logs in) and mine (which can decrypt old messages).

Can anyone give me some pointers as to whether this is related to the `Session key: <not supported>` in this ticket.

Her browser is set to clear cache and she has enters her backup password each time she opens her browser and logs into element.4d2.org. My expectation is that manually entering the backup key would provide access to all messages, but it seems to only be a subset of them (more recent ones). We also tried the "Restore from Backup" button under Security & Privacy and that didn't have any effect. Who can read for the room is set to "members since they were invited".

PS I've very familiar with https://github.com/element-hq/element-meta/issues/245 and I thought all those problems were behind us with Element R. If there's a specific issue that I should look at, please point me to it so I can continue running tests to understand what's going wrong here.

**Comment by richvdh** [comment]
@hax0rbana-adam: `Session key: <not supported>` is essentially normal in modern versions of Element Web R. It is entirely cosmetic.

Please open a separate issue if you want to discuss further as it's off-topic here, but in short: key backup is a server-side *backup*. You need an active client to receive the keys in the first place; it sounds like your user does not have such a device. The long-term solution to this is [dehydrated devices](https://github.com/element-hq/element-meta/issues/922) but this remains under development.
