### ISSUE TITLE
New compound button colors feel very bright and aggressive in the dark theme.

### ISSUE THREAD

**Issue by MTRNord** [element-hq/element-web#27006]
### Steps to reproduce

1. Open the settings for example

#### What did you expect?

A theme that is not disturbing to look at for long times

#### What happened instead?

![image](https://github.com/element-hq/element-web/assets/1374914/2e8657fc-f03e-4a6e-9b74-17a05f031430)

The buttons have very harsh contrasts, making it hard for me to read and look at them for extended amounts of time (aka anything more than 30s).

### Operating system

Fedora Silverblue 39

### Browser information

Firefox 121.0.1 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: 92c831094d11-react-ed5ef023b24b-js-d03db1740586 Krypto-Version: Rust SDK 0.7.0 (fac36bc), Vodozemac 0.5.1

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

No

**Comment by robintown** [comment]
Because these parts of the interface weren't designed with the new Compound colors in mind, we're definitely overapplying those bright, punchy primary buttons here. This situation will get better as we redesign more of the application to use Compound buttons in a way that matches their visual weight, but I think changing some of these buttons to secondary ahead of a redesign is also reasonable.

**Comment by robintown** [comment]
On the second iteration of this change (https://github.com/matrix-org/matrix-react-sdk/pull/12299) I changed some of these buttons to secondary where appropriate.
