### ISSUE TITLE
Room knocking via spaces doesn't work

### ISSUE THREAD

**Issue by sdrgeek** [element-hq/element-web#27025]
### Steps to reproduce

1. View Rooms via Space. 
2. Press join button on knocking enabled Room.
![image](https://github.com/element-hq/element-web/assets/81026491/f0ce295b-6709-4405-be81-5f679f667c5e)

3. Get this error message:
![image](https://github.com/element-hq/element-web/assets/81026491/1216ce6e-ecf4-433c-aba0-b70b863b565c)

#### What did you expect?
starting a join request
#### What happened instead?
HTTP 403

### Browser information

Firefox 115.6.0esr (64-bit)

### Application version

element-web 1.11.58

### Will you send logs?

Yes

**Comment by sdrgeek** [comment]
correlates to #18655

**Comment by 0x5ECF4ULT** [comment]
I, too, want to express the importance of this feature. I'm a co-admin for a organizational server. We're joining new users on our HS automatically into a space, but members already having an account on another HS should be able to participate in certain rooms in this space as well. So we just tell them to join the space. We don't want to open this room to the public since the room is, well, members only.
Enabling knocking via rooms would enable said use-case.
