### ISSUE TITLE
Visual appearance of dangerous buttons inconsistent

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27179]
### Steps to reproduce

1. Go to Settings
2. Observe buttons with a delete action

#### What did you expect?
Consisten appearance

#### What happened instead?
Buttons have different styles, outline and filled

![image](https://github.com/element-hq/element-web/assets/640121/56d2cf8a-3a7c-4372-9322-f41e3adf1330)
![image](https://github.com/element-hq/element-web/assets/640121/b0798f17-c87b-45b3-b27f-c0077f151fcb)

### Operating system

Windows 11

### Application version

Element version: 1.11.60 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

No

**Comment by kongo09** [comment]
Not sure if this is the same. There can be a case when a single button is highlighted to guide a user in a flow towards the next best action. A dangerous destructive RED button is typically never a next best action but a conscious special action.

**Comment by daniellekirkwood** [comment]
Added this to the list of issues as a part of the settings project

**Comment by kongo09** [comment]
Redesign still has two different button styles (2nd level and 3rd level) in different places.

**Comment by americanrefugee** [comment]
I've made the following changes, based on trying out different buttons styles to determine what looks best and minimizes scary features:

- **Sign out buttons for the user's account and on the device detail page** are _secondary_
   - When I tried tertiary styles / text links, it became too difficult to spot
   - Since some users will need to sign in and out every day, I felt that it was important to make this instance of a "destructive" button more prominent
- **Sign out buttons for the device list (either OIDC or Legacy)** are _text links / tertiary_
- Likewise, **for all other destructive actions** are also _text links / tertiary_

For reference, [here's an example of a page with both styles](https://www.figma.com/file/qTWRfItpO3RdCjnTKPu4mL/Settings?type=design&node-id=45-18175&mode=design&t=LkYdPBTEg9U7NyDs-4).

Also, here is a [device list](https://www.figma.com/file/qTWRfItpO3RdCjnTKPu4mL/Settings?type=design&node-id=119-16442&mode=design&t=LkYdPBTEg9U7NyDs-4) and [device details](https://www.figma.com/file/qTWRfItpO3RdCjnTKPu4mL/Settings?type=design&node-id=119-19526&mode=design&t=LkYdPBTEg9U7NyDs-4) pages.

**Comment by kongo09** [comment]
Great point about the sign-out which indeed is a policy in some environments, which elevates it.

**Comment by daniellekirkwood** [comment]
Great, sounds like we've found the right compromise. The design files have been updated and the logic of where and why we use which button type agreed upon. Closing this task.
