### ISSUE TITLE
Clicking on the "Threads" text to show the Threads Activity Center causes it to be dismissed immediately

### ISSUE THREAD

**Issue by langleyd** [element-hq/element-web#27335]
### Steps to reproduce

1. Go to Notifications Settings and enabled all activity in the Threads Activity Center 
2. Expand Spaces list so that you can see the TAC "Threads" text fully
3. Click on the upper half of the "Threads" text

#### What did you expect?
The TAC opens

#### What happened instead?
The TAC opens on the down click and is dismissed up the up click and the last row in the TAC is selected.

### Operating system

macOS

### Browser information

Version 123.0.6312.122 (Official Build) (x86_64)

### URL for webapp

develop

### Application version

Element version: 8ce46d3de88e-react-6392759bec51-js-843853353204 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by dbkr** [comment]
So, this is radix doing this: https://github.com/radix-ui/primitives/blob/main/packages/react/menu/src/Menu.tsx#L647 combined with the fact that the popup appear as if it came from just the icon, rather than the 'Threads' label, and therefore appears over the 'Threads' label so the newly created popup catches the mouseup and generates a click, immediately selecting whatever was under the cursor.

The only options I can think of for fixing this are:
 1. Convince radix that this is a bug and requires tracking the mousedown events so we ignore mouseups if the mousedown didn't occur within the menu
 2. Horrendous hack like ignoring item selections for the first 10ms after the menu opens 🤮
 3. Move the menu to the right of the label if the spaces panel is expanded.

Opinions? Should the TAC be to the right of the label anyway?
