### ISSUE TITLE
Blank page when using app.element.io with Firefox 124

### ISSUE THREAD

**Issue by hishamhm** [element-hq/element-web#27717]
### Steps to reproduce

Opening app.element.io brings up a blank page. This is not Firefox ESR as reported in previous issues.

#### What did you expect?

For Element to start.

#### What happened instead?

A blank page.

### Operating system

Ubuntu Linux 22.04.1 LTS

### Browser information

Firefox 124.0.1 (64-bit)

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No (I cannot reach the Element application)

**Comment by t3chguy** [comment]
Firefox 124 is unsupported just the same as ESR - see policy at https://github.com/element-hq/element-web#supported-environments

Firefox release is up to 128 https://whattrainisitnow.com/ so only 127 & 128 are supported at this time.

The fix for the blank page instead of a sane error has already landed and will roll out in the next release.

You may wish to voice your opinion at https://github.com/element-hq/element-web/issues/27684 if you think the Firefox policy should be >=124.
