### ISSUE TITLE
Unsupported browser (Firefox 128.0)

### ISSUE THREAD

**Issue by zc-devs** [element-hq/element-web#27793]
### Steps to reproduce

1. Open Firefox 128
2. Open https://app.element.io/

#### What did you expect?

Worked app

#### What happened instead?

![Not worked app](https://github.com/user-attachments/assets/8682a855-6068-4c1a-9851-0e4782370b28)

### Operating system

Windows

### Browser information

Firefox 128.0 (is it modern enough? :-D

### URL for webapp

https://app.element.io/

### Will you send logs?

No, cause I cannot `send a /rageshake command from the web application`

**Comment by zc-devs** [comment]
I'm not using Element anymore, so this is not `Major` for me. It is JFYI :)

**Comment by t3chguy** [comment]
Your browser is missing WebAudio. https://developer.mozilla.org/en-US/docs/Web/API/AudioContext

You likely have it disabled in `about:config`, this isn't a supported environment if it doesn't meet the featureset the vendor claims. Mozilla claims Firefox supports AudioContext from v25 onwards.

**Comment by zc-devs** [comment]
> closed this as not planned

I didn't expect anything else

> Your browser is missing WebAudio. You likely have it disabled in about:config.

Yup. You are right. I do not need it to chat in a one public project's room.

Besides, it worked until yesterday I hit F5.

**Comment by t3chguy** [comment]
> Besides, it worked until yesterday I hit F5.

Element has been using Web Audio for probably a year and a half, recently a community member contributed a fix for Element showing up as an audio service due to it playing ringtones and ported that to use AudioContext as that is the only way browsers provide to hide yourself as a media playback site for background audio.

https://github.com/matrix-org/matrix-react-sdk/pull/10995
