### ISSUE TITLE
"Unable to decrypt message" eror when trying to read messages in an E2EE chat

### ISSUE THREAD

**Issue by Overstuff1260** [element-hq/element-web#28090]
### Steps to reproduce

1. Log in in your Element Account
2. Open E2EE chat
3. Not reading anything

#### What did you expect?
reading messages
#### What happened instead?
"unable to decrypt" error every message

### Operating system

Windows 10

### Browser information

Firefox 130.0

### URL for webapp

app.element.io

### Application version

version Element: 1.11.77 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Will you send logs?

Yes

**Comment by dav9597** [comment]
probably this issue is referred to this one https://github.com/element-hq/element-meta/issues/245

**Comment by richvdh** [comment]
@strypey: please send debug logs from within the application, *and* from your android device. I suggest creating a new issue, so that it doesn't get mixed up with @dav9597's issues.

@dav9597: I see your debug logs, but please give more info. Does this affect newly-received messages, or only ones sent before you logged in? Did you verify your session after login? Do you have any other devices (eg mobile, other element-web sessions)?

**Comment by dav9597** [comment]
Hi, my answers:

- Does this affect newly-received messages, or only ones sent before you logged in? I haven't really checked this, now I noticed that an user replied to my message in an E2EE chat, and I can see it probably because he replied directly to mine, not sure. However I attached updated logs, hope this helps
[logs.zip](https://github.com/user-attachments/files/17110244/logs.zip)


Did you verify your session after login? Yes, I did

Do you have any other devices (eg mobile, other element-web sessions)? Yes, as specified in log's note, I have a Brave Chromium session too with same errors, of course web access

**Comment by Overstuff1260** [comment]
changed username per personal reasons, but it's still me

**Comment by richvdh** [comment]
It sounds like you are seeing expected behaviour.

In general, you will not be able to decrypt messages sent before you logged in. This is rather the point of end-to-end encryption: if you can see history simply by logging in, then an attacker would also be able to do so.

The exception to this is when you have a second device which does successfully receive the message keys. In that case, the other device can encrypt the message keys and upload them to a server-side storage area, where they can be retrieved by another device. However, if all your devices have the same problem (they were created *after* the messages were sent), that doesn't help.

There is a plan to improve this with [device dehydration](https://github.com/element-hq/element-meta/issues/922), but that is several months away.

**Comment by strypey** [comment]
Thanks @richvdh, done; https://github.com/element-hq/element-web/issues/28116
