### ISSUE TITLE
Why is the latest browser version not supported in Tor?

### ISSUE THREAD

**Issue by azarenkovgd** [element-hq/element-web#28147]
Why is the latest browser version not supported in Tor?

It's unfortunate that the Element client for Matrix is not available on Tor, as it limits access to secure, decentralized communication for those who prioritize privacy and anonymity.

It seems natural that a client like Element should be available on Tor. Moreover, it feels like something that should be implemented as a priority.

**Comment by t3chguy** [comment]
Tor is built on an over a year old Firefox version which lacks many web features around encryption, i18n and the like. Once Tor updates to the latest Firefox ESR it'll work once again. Due to lack of funding Tor is not considered a supported browser, there's also no way for us to run tests against Tor as Playwright does not support it.
