### ISSUE TITLE
Unable to decrypt messages for previous messages in my rooms

### ISSUE THREAD

**Issue by patriknorlander** [element-hq/element-web#28161]
### Steps to reproduce

When logging in I was asked to verifiy with other device or with passphrase. Entered passphrase. Get unable to decrypt messages in all my chats.

### Operating system

WIndows 11

### Browser information

Edge: Version 128.0.2739.67 

### URL for webapp

app.element.io

### Application version

Element-version: 1.11.79 Kryptoversion: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by danielcb** [comment]
We've also got this problem. 6 users in sum. Migrated from synapse/element-web to synapse/matrix-authentication-service/element-web.

All users need to re-verify, which all users did. Everything works for 5 of the users. One user sees only 'Unable to decrypt message' for all previous messages, although the verification succeeded and all his sessions are shown as verified.

**Comment by richvdh** [comment]
We investigated the problem for the original reporter. 

In short, key backup was not signed by the user's keys. Most likely, that happened because key backup had been reset from a device which was not verified and therefore did not have the cross-signing keys, so could not sign the backup.

Unfortunately, that happened some time ago, so we lack client-side and server-side logs as to how that could have taken place (or even which platform the relevant device was on).

@danielcb if you are still having problems, please open a new issue, and send debug logs from within the affected client(s).
