### ISSUE TITLE
Message from a previously-verified user has a shield stating "Unknown error"

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#28170]
### Steps to reproduce

1. Two users who have verified each other using the emoji dance
2. Reset identity of the sender
3. To make sure, type `/discardsession` as the sender
4. Send a message from the sender

#### What did you expect?

I expected a shield saying "sent from a user in verification violation" (or better words)

#### What happened instead?

![image](https://github.com/user-attachments/assets/ced35d08-f538-46c8-ad31-b6f0717848e8)

I saw "Unknown error" when hovered over the shield and the log said:

```
 Unknown shield state message 'Encrypted by a previously-verified user.'
```

### Operating system

Debian 12.7

### Browser information

Firefox 130.0

### URL for webapp

https://develop.element.io

### Application version

Element version: 8d77b2a15ae5-react-df4a223eb621-js-b842192a3415 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Will you send logs?

No

**Comment by uhoreg** [comment]
Taking a quick look at this (I'm not self-assigning this because it's near the end of my day, but I may do so tomorrow if nobody else picks this up):

The icon seems to be determined in `components/views/rooms/EventTile.tsx` in the `renderE2EPadlock` function, and takes the tooltip from based on `this.state.shieldReason`, which is an `EventShieldReason` from `matrix-js-sdk/src/crypto-api/index.ts`, and gets set from `rustEncryptionInfoToJsEncryptionInfo` in `matrix-js-sdk/src/rust-crypto/rust-crypto.ts`.  But it doesn't look like we have an `EventShieldReason` for verification violation yet.  So we need to

- add a new `EventShieldReason` code,
- change `rustEncryptionInfoToJsEncryptionInfo` to emit that code,
- get `renderE2EPadlock` to understand that code,
- and add a new string for that code.

While we're in that area, we may also want to check what other codes we need to add.  Also, given that we need to modify `rustEncryptionInfoToJsEncryptionInfo` already, we may want to convert it to using the shield state codes rather than the messages, as it shouldn't be much extra work, and will save us effort in the future.
