### ISSUE TITLE
Username mentions are not handled properly when display name mentions are disabled

### ISSUE THREAD

**Issue by composite9239** [element-hq/element-web#28335]
### Steps to reproduce

1. Set notifications for "Messages containing my display name" to "Off"
2. Set notifications for "Messages containing my username" to "Noisy"
3. Tag yourself in another Element client such that you get the Element "mention-bubble" of the user, not just the raw username
4. Get no notification despite being tagged directly

#### What did you expect?

Receiving a noisy notification since a tag-bubble should be equivalent to the username being typed out.

#### What happened instead?

Received no notification. For `@user:example.com` it only sends a notification if `user` is typed, whereas it should notify for the full username (either someone typing `@user:example.com` or the Element mention-bubble version of that). I do not see the use case for people being notified for their bare username being written out so I assume this is not intended behavior. Tagging someone via message bubble should notify them if they want to be notified of their username being used.

### Operating system

Ubuntu

### Application version

Element version: 1.11.82 Crypto version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Homeserver

Synapse 1.117.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
That's because pills only include the user's displayname in the `body` field which is what the server-side push rule checks for. 

> Receiving a noisy notification since a tag-bubble should be equivalent to the username being typed out.

That just isn't the case in Matrix spec https://spec.matrix.org/v1.12/client-server-api/#user-and-room-mentions

The proper solution to this is intentional mentions, which relies on the sender sending an `m.mentions` field in the event, your server supporting intentional mentions and the `.m.rule.is_user_mention` rule being enabled. 

For any further investigation we would need to see

1. Logs
2. Your push rules from /devtools
3. The event source for the event not pinging you

**Comment by composite9239** [comment]
Would it be more appropriate for me to raise the issue in the Synapse repository so that the server-side push rule could be changed to also check the `formatted_body` field and notify `user` if it contains `a href=\"https://matrix.to/#/@user:example.com\"`, for the username mentions setting specifically?

**Comment by t3chguy** [comment]
@composite9239 such a suggestion would need to be made to the Matrix spec, not the repo of just one server implementation. The Matrix spec specifies which fields to check on the built-in push rules.
