### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by rex4539** [element-hq/element-web#28368]
### Steps to reproduce

1. Log in to Element.

#### What did you expect?
No memory leaks.
#### What happened instead?
```
2024-11-03T03:50:43.127Z W Possible EventEmitter memory leak detected. 11 RoomState.events listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 RoomState.events listeners added. Use emitter.setMaxListeners() to increase limit
2024-11-03T03:50:44.792Z W Possible EventEmitter memory leak detected. 11 RoomState.members listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 RoomState.members listeners added. Use emitter.setMaxListeners() to increase limit
```

### Operating system

macOS 15.1

### Application version

Element Nightly 2024110101

### How did you install the app?

https://packages.element.io/nightly/install/macos/index.html

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by rex4539** [comment]
[log-1.log](https://github.com/user-attachments/files/17609363/log-1.log)

**Comment by t3chguy** [comment]
11 listeners makes a memory leak not. If it was hundreds or growing then it'd be a leak. This is just a very shared model.

**Comment by aral-matrix** [comment]
this issue is still happening. @t3chguy I do not understand your "This is just a very shared model" statement - Well written code doesn't warn about possible memory leaks just because a certain amount of classes is instantiated. If anything, there's a limit beyond which new instances won't be created & that would trigger an exception. If the application needs more instances, then the limit needs to be high enough...
