### ISSUE TITLE
What happened to the Security Phrase verification option?

### ISSUE THREAD

**Issue by bobbyl140** [element-hq/element-web#28477]
### Steps to reproduce

I realize this isn’t quite a “bug report” but it’s closer to that than a feature request: what happened to the option to verify a session with the Security Phrase? That was a user-memorable string whereas the other options require a file or another device. I used the Security Phrase for access without having another device or the security key file and now cannot. Is this a setting or was it removed as a feature? Thank you. 

### Outcome

N/A

### Operating system

macOS 15.2

### Browser information

Safari 18.2

### Application version

v1.11.85

### Homeserver

Synapse 0.34.0.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
I believe the product team chose to remove it due to the amount of users that got confused by having two passwords effectively, it also didn't play well with password managers for that purpose. The main way they want this done is using an existing device, falling back to you "Recovery Key". https://github.com/element-hq/element-meta/discussions if you want to discuss it.
