### ISSUE TITLE
Cannot leave a room

### ISSUE THREAD

**Issue by progval** [element-hq/element-web#28599]
### Steps to reproduce

1. Try to leave `!wkyjxWeAOBpKMvHbno:matrix.org` (former Codeberg room, that got upgraded)

#### What did you expect?

I expected to leave the room

#### What happened instead?

`MatrixError: [403] @pinkie:matrix.org not in room !wkyjxWeAOBpKMvHbno:matrix.org. (https://matrix-client.matrix.org/_matrix/client/v3/rooms/!wkyjxWeAOBpKMvHbno%3Amatrix.org/leave)`

The room also keeps showing as having a notification.

I used to not be able to see the content of the room (#28479, which was mistakenly closed as duplicate).

### Operating system

Debian 12

### Browser information

Firefox 128.5.0esr

### URL for webapp

https://riot.im/app/

### Application version

Element version: 1.11.86 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is an issue on the server not the client, if the server sent you a room via `/sync` `join` then it should allow you to leave it, it might be due to a bad cache so you could try clear cache in settings but either way not something a client should be having to workaround. matrix.org uses Synapse so you could open an issue there.
