### ISSUE TITLE
Labs option "Element Call video rooms" is not able to be toggled off under any conditions

### ISSUE THREAD

**Issue by benparsons** [element-hq/element-web#28677]
#### What would you like to do?

Toggle off the "Element Call video rooms" in Labs.

#### Why would you like to do it?

Customer would like to do this _for now_ to improve user understanding.

#### How would you like to achieve it?

Make that option available.

### Have you considered any alternatives?

The goal is to get onto EC. For now they just need to hide the option.

**Comment by t3chguy** [comment]
This is intentional and was signed off by the product team for our main packages & deployments. It is how the config.json for labs works. Closing in favour of https://github.com/element-hq/element-web/issues/24209 which would enable it to be toggled off. I suggest you help the customer disable it in their config.json.
