### ISSUE TITLE
Importing from key export file should report success / fail

### ISSUE THREAD

**Issue by jryans** [element-hq/element-web#9445]
When you import from a key export, it seems to just close the dialog without saying whether it worked or not, which is not very reassuring for such an important workflow.

We should clearly communicate the outcome (success / failure) to the user.

**Comment by xloem** [comment]
It would also be great if there were some way to discern this, until such a feature is implemented, like some textual debug output.  Key import doesn't appear to be working for me right now.

**Comment by ShadowJonathan** [comment]
This is still applicable, however, it *does* tell you if you entered the wrong passphrase.

**Comment by daniellekirkwood** [comment]
Are we referencing this screen?

<img width="1438" alt="Screenshot 2022-04-27 at 12 33 31" src="https://user-images.githubusercontent.com/89144281/165606930-b20e5620-28a5-4830-b681-502730e237a6.png">

**Comment by t3chguy** [comment]
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.

**Comment by xloem** [comment]
I had basically stopped using element years ago because of issues like these — I couldn’t retain encrypted conversations from use to use, and didn’t find channels to address this. Sorry the connection didn’t form.

If key exchange is working for devs, it’s possible people complaining of issues are using compromised devices. More debug output, and/or clear information on what the correctly functioning flow is, could make that easier to discern
