### ISSUE TITLE
Provide option to use system / native emojis

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#9790]

**Comment by aaronraimist** [comment]
keyword: native emoji

**Comment by strixaluco** [comment]
That would be great, because Riot 1.2.2 version brought new emoji set, which doesn't look quite as nice as previous. 
In fact, Riot 1.2.0 was rendering emoji with native Noto font perfectly fine and I liked it better.
OS: Debian buster/sid

**Comment by kevincox** [comment]
It seems that this can be fixed/worked around by using a "custom" font. You can go to `Preferences -> Appearance -> Show Advanced -> Use a system font -> Enter "sans-serif"` and it will use your browsers default sans-serif font and emoji. (I assume this works for "serif" or custom fonts as well)

**Comment by julianfairfax** [comment]
> It seems that this can be fixed/worked around by using a "custom" font. You can go to `Preferences -> Appearance -> Show Advanced -> Use a system font -> Enter "sans-serif"` and it will use your browsers default sans-serif font and emoji. (I assume this works for "serif" or custom fonts as well)

As of the time of writing this, the default font-family on my Flatpak installation is `Inter,Twemoji,Apple Color Emoji,Segoe UI Emoji,STIXGeneral,Arial,Helvetica,sans-serif,Noto Color Emoji`

By default, this also uses Twemoji for me. You can remove Twemoji from that list, but it than uses san-serif first, since for some reason that's ahead of Noto Color Emoji.

So the cleanest and simplest solution is to simply set your system font to `Inter,Noto Color Emoji,Apple Color Emoji,Segoe UI Emoji,STIXGeneral,Arial,Helvetica,sans-serif,Noto Color Emoji`.

**Comment by hex-m** [comment]
related: https://github.com/vector-im/element-web/issues/26260

**Comment by HarHarLinks** [comment]
isn't this done?
![image](https://github.com/element-hq/element-web/assets/2803622/b11979ca-d185-41ef-9d6c-4df06544a256)

**Comment by t3chguy** [comment]
Yup
